services:
  mongo:
    image: mongo
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}

  postgres:
    image: postgres:18-alpine
    ports:
      - ${POSTGRES_PORT}:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/18/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  gateway:
    ports:
      - ${GATEWAY_PORT}:80
    build: ./gateway
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
    environment:
      - PORT=${GATEWAY_PORT}
      - USER_AUTH_URL=http://user-auth:${USER_AUTH_PORT}
      - USER_ACCESS_URL=http://user-access:${USER_ACCESS_PORT}

  eclipse:
    image: eclipse-mosquitto
    ports:
      - ${ECLIPSE_MQTT_PORT}:1883
      - ${ECLIPSE_WS_PORT}:9001

  iot-ingest:
    build: ./iot-ingest-service
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
    environment:
      - ECLIPSE_MQTT_BROKER=eclipse
      - ECLIPSE_MQTT_PORT=${ECLIPSE_MQTT_PORT}
      - ECLIPSE_WS_PORT=${ECLIPSE_WS_PORT}
      - MONGO_URI=mongodb://mongo:${MONGO_PORT}/${MONGO_INITDB_DATABASE}
      - DEVICE_JWT_SECRET=${DEVICE_JWT_SECRET}

  iot-auth:
    build: ./iot-auth-service
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
    environment:
      - PORT=${IOT_AUTH_PORT}
      - DEVICE_JWT_SECRET=${DEVICE_JWT_SECRET}

  user-auth:
    build: ./user-auth-service
    ports:
      - ${USER_AUTH_PORT}:${USER_AUTH_PORT}
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
    environment:
      - FLASK_RUN_PORT=${USER_AUTH_PORT}
      - FLASK_RUN_HOST=0.0.0.0
      - USER_JWT_SECRET=${USER_JWT_SECRET}
      - POSTGRES_URI=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:${POSTGRES_PORT}/${POSTGRES_DB}

  user-access:
    build: ./user-access-service
    ports:
      - ${USER_ACCESS_PORT}:${USER_ACCESS_PORT}
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
    environment:
      - FLASK_RUN_PORT=${USER_ACCESS_PORT}
      - FLASK_RUN_HOST=0.0.0.0
      - USER_JWT_SECRET=${USER_JWT_SECRET}
      - POSTGRES_URI=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:${POSTGRES_PORT}/${POSTGRES_DB}
      - MONGO_URI=mongodb://mongo:${MONGO_PORT}/${MONGO_INITDB_DATABASE}
      - MONGO_DB_NAME=${MONGO_INITDB_DATABASE}

volumes:
  db_data:
  mongo_data:
