services:
  mongo:
    image: mongo
    ports:
      - ${MONGO_PORT}:27017
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    networks:
      - ssa-iot-ingest-services-network

  postgres:
    image: postgres:18-alpine
    ports:
      - ${POSTGRES_PORT}:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/18/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - ssa-iot-ingest-services-network

  traefik:
    image: traefik:v2.10
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--providers.docker.network=ssa-iot-ingest-services-network"
      - "--api.dashboard=true"
    ports:
      - "8080:80"
      - "8081:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - ssa-iot-ingest-services-network

  eclipse:
    image: eclipse-mosquitto
    ports:
      - ${ECLIPSE_MQTT_PORT}:1883
      - ${ECLIPSE_WS_PORT}:9001
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - ssa-iot-ingest-services-network

  iot-ingest:
    build: ./iot-ingest-service
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
    depends_on:
      - eclipse
      - mongo
    environment:
      - ECLIPSE_MQTT_BROKER=eclipse
      - ECLIPSE_MQTT_PORT=${ECLIPSE_MQTT_PORT}
      - MONGO_URI=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:27017
      - MONGO_DB_NAME=${MONGO_INITDB_DATABASE}
      - DEVICE_JWT_SECRET=${DEVICE_JWT_SECRET}
    networks:
      - ssa-iot-ingest-services-network

  iot-auth:
    build: ./iot-auth-service
    ports:
      - ${IOT_AUTH_PORT}
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
    depends_on:
      postgres:
        condition: service_healthy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.iot-auth.rule=PathPrefix(`/iot/auth/`)"
      - "traefik.http.services.iot-auth.loadbalancer.server.port=${IOT_AUTH_PORT}"
      - "traefik.http.routers.iot-auth.entrypoints=web"
    environment:
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=${IOT_AUTH_PORT}
      - DEVICE_JWT_SECRET=${DEVICE_JWT_SECRET}
      - POSTGRES_URI=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:${POSTGRES_PORT}/${POSTGRES_DB}
    networks:
      - ssa-iot-ingest-services-network

  user-auth:
    build: ./user-auth-service
    ports:
      - ${USER_AUTH_PORT}
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
    depends_on:
      postgres:
        condition: service_healthy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.user-auth.rule=PathPrefix(`/user/auth/`)"
      - "traefik.http.services.user-auth.loadbalancer.server.port=${USER_AUTH_PORT}"
      - "traefik.http.routers.user-auth.entrypoints=web"
    environment:
      - FLASK_RUN_PORT=${USER_AUTH_PORT}
      - FLASK_RUN_HOST=0.0.0.0
      - USER_JWT_SECRET=${USER_JWT_SECRET}
      - POSTGRES_URI=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:${POSTGRES_PORT}/${POSTGRES_DB}
    networks:
      - ssa-iot-ingest-services-network

  user-access:
    build: ./user-access-service
    ports:
      - ${USER_ACCESS_PORT}
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
    depends_on:
      postgres:
        condition: service_healthy
      mongo:
        condition: service_started
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.user-access.rule=PathPrefix(`/user/access/`)"
      - "traefik.http.services.user-access.loadbalancer.server.port=${USER_ACCESS_PORT}"
      - "traefik.http.routers.user-access.entrypoints=web"
    environment:
      - FLASK_RUN_PORT=${USER_ACCESS_PORT}
      - FLASK_RUN_HOST=0.0.0.0
      - USER_JWT_SECRET=${USER_JWT_SECRET}
      - POSTGRES_URI=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:${POSTGRES_PORT}/${POSTGRES_DB}
      - MONGO_URI=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:27017
      - MONGO_DB_NAME=${MONGO_INITDB_DATABASE}
    networks:
      - ssa-iot-ingest-services-network

volumes:
  db_data:
  mongo_data:

networks:
  ssa-iot-ingest-services-network:
    driver: bridge
